<a href="https://colab.research.google.com/github/Shraddha-Ramteke/Data-Analysis-for-Python/blob/main/NumPy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy exercises**

In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.5


# Array creation
 Create a numpy array of size 10, filled with zeros.

In [2]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create a numpy array with values ranging from 10 to 49

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [10]:
X = np.arange(4, dtype=np.int64)

np.ones_like(X)

array([1, 1, 1, 1])

# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [9]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

#  Create a numpy matrix of 4*4 integers, filled with fives.

In [13]:
np.ones([4,4], dtype=np.int64) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#  Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.


In [14]:
X = np.array([[2,3], [6,2]], dtype=np.int64)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [15]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a numpy array, filled with 3 random integer values between 1 and 10.

In [16]:
np.random.randint(10, size=3)

array([9, 1, 9])

# Create a 3*3*3 numpy matrix, filled with random float values.

In [17]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 1.12762716, -0.4786659 , -0.35678082],
        [ 0.18959704,  0.42145628, -0.10493037],
        [ 2.40618812, -0.8570326 , -2.15069122]],

       [[-0.02249214,  0.36079879, -0.19506206],
        [-1.80825477, -0.86693217,  0.39135301],
        [-0.20930554,  0.20387663, -0.68397372]],

       [[-1.25951506,  1.92898534,  0.4644764 ],
        [-1.25375712,  0.99829957,  1.16226636],
        [-0.0121893 ,  0.83570033, -0.26739493]]])

# Given the X python list convert it to an Y numpy array

In [18]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


# Given the X numpy array, make a copy and store it on Y.

In [19]:
X = np.array([5,2,3], dtype=np.int64)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 139661750144336
[5 2 3] 139661750144720


# Create a numpy array with numbers from 1 to 10

In [20]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Create a numpy array with the odd numbers between 1 to 10

In [21]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

# Create a numpy array with numbers from 1 to 10, in descending order.

In [22]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [23]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Show the memory size of the given Z numpy matrix

In [24]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# Array indexation
 Given the X numpy array, show it's first element


In [25]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

# Given the X numpy array, show it's last element

In [26]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'

# Given the X numpy array, show it's first three elements

In [27]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

# Given the X numpy array, show all middle elements

In [28]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

# Given the X numpy array, show the elements in reverse position

In [29]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

# Given the X numpy array, show the elements in an odd position

In [30]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

# Given the X numpy matrix, show the first row elements

In [31]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

# Given the X numpy matrix, show the last row elements

In [32]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

# Given the X numpy matrix, show the first element on first row

In [33]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

# Given the X numpy matrix, show the last element on last row

In [34]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

# Array manipulation
Convert the given integer numpy array to float

In [35]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float64)

array([-5., -3.,  0., 10., 40.])

# Reverse the given numpy array (first element becomes last)

In [36]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

# Order (sort) the given numpy array

In [37]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

# Given the X numpy array, set the fifth element equal to 1

In [38]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# Given the X numpy array, change the 50 with a 40

In [39]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

# Given the X numpy matrix, change the last row with all 1

In [40]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

# Given the X numpy matrix, change the last item on the last row with a 0

In [41]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

# Boolean arrays (also called masks)
Given the X numpy array, make a mask showing negative elements

In [42]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

# Given the X numpy array, get the negative elements

In [43]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

# Given the X numpy array, get numbers higher than 5

In [44]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

# Logic functions
Given the X numpy array, return True if none of its elements is zero

In [45]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

# Given the X numpy array, return True if any of its elements is zero

In [46]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True